spring.application.name=KidsParades
# 1. SQLite Connection String (it will create kids_paradis.db in your project folder)
spring.datasource.url=jdbc:sqlite:kids_parades.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# 2. Hibernate Settings for SQLite
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.show-sql=false

# 3. Handling Arabic Characters correctly in SQLite
spring.datasource.connection-properties=characterEncoding=utf-8